Improvement/holo 681 update prettier rules for holograph protocol
holographxyz/v2 pull request #116
Opened 2022-12-22 11:59 UTC by BravoNatalie

## Describe Changes

Since [prettier ends all files with a new line by design](https://github.com/prettier/prettier/issues/6360) and there's no option to disable this, the solution here is to add the empty line to the end of all files that are being changed by prettier.

- Changed `abi` task by adding an empty line at the end of the ABI files.
- Created `deploymentsPrettier` task to add a new line at the end of the deployments files.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] Code styles have been enforced
- [x] All Hardhat tests are passing

2022-12-22 18:10 UTC, alexanderattar commented on hardhat.config.ts
> +    files.forEach(function (file) {
Nit: can this be updated to also use `for (const file of files) {` for consistency

2022-12-22 18:11 UTC, alexanderattar approved these changes
Glad to have this annoying thing fixed finally! 👏

2022-12-27 19:46 UTC, sogoiii requested changes
@BravoNatalie @alexanderattar Ok i think we have to add this task as part of the "compile" and /or the deploy script in package.json? So we don't have to "remember" to run the command manually.

2022-12-27 21:28 UTC, sogoiii approved these changes
👍

2022-12-27 21:28 UTC, merged