Feature/precomput hashes script
holographxyz/v2 pull request #259
Opened 2024-04-04 00:58 UTC by alexanderattar

## Describe Changes

- Add a pre-commit command that runs the precompute slot script
- Make it so the precompute slot script updates any slots that are found

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] All Hardhat tests are passing

2024-04-04 13:34 UTC, Yashiru approved these changes
Nice 👌

2024-04-04 23:05 UTC, sogoiii requested changes

2024-04-04 23:05 UTC, sogoiii commented on README.md
> +2. On commit, the pre-commit script will run and update the contents of the `precompute` slot function into the output of the hash that is actually stored in the contract.
@alexanderattar Its great that this works via the git commit hook. But I think that the hook is the safety net, not the primary dev work flow. I think we should describe how the developer should use the script by calling it manually. Because I would imagine we are adding a slot, and updating a test somewhere. its weird to require doing a commit to force the conversion. 

## Maybe something like this

1. Add a variable to your contracts storage such as `bytes32 constant _interfacesSlot = precomputeslot("eip1967.Holograph.interfaces");`. Add slots below existing slots. Never add them in between existing slots. 
2. Run the `npx ts-node scripts/precompute-solidity-hashes.ts` script to update the contents of the `precompute` slot function into the output of the hash that is actually stored in the contract.
3. Annotate the converted line with a comment so the original value is captured. See existing slot to see how we comment these values. We should be able to see what the string version of the hash is.
4. These constants provide access to important variables at a unique location in a consistent manner.

Note, that if you do not manually call the `precompute-solidity-hashes.ts` script, we have a git hook that will automatically convert it.

2024-04-05 00:11 UTC, sogoiii approved these changes
👍

2024-04-05 00:11 UTC, merged