Feature / HOLO 1495 CustomContract Reveal CSV File
holographxyz/v2 pull request #272
Opened 2024-04-17 17:01 UTC by BravoNatalie

## Describe Changes

I made this more better by doing ...

- Change A
- Change B

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] All Hardhat tests are passing

2024-05-01 23:06 UTC, sogoiii requested changes
I think this is a great start! We can work on improving the tutorials. 👍

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +## Script 2: Set Owner
@BravoNatalie since this method is not working yet. we should call it out here so they do not try to do this.

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +2. **Set the static values:**
@BravoNatalie numbering is off. Should start with 1. Also What file should i modify?

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +2. **Set the static values:**
@BravoNatalie number should start with 1.

2024-05-01 23:06 UTC, sogoiii commented on scripts/custom_delay_reveal_erc721/utils.ts
> +import path from 'path';
@BravoNatalie this file looks like the other one. I think we can move it to `scripts/utils/utils.ts`

2024-05-01 23:06 UTC, sogoiii commented on deploy/30_verify.ts
> +      'CountdownERC721',
@BravoNatalie we should have this commented out like the other contracts.

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +### Steps
@BravoNatalie Add a comment that references the file comment. I was sorta confused on initial read what these sections where and what they referenced.

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/4-purchase.ts
> +  const price = ethers.utils.parseUnits('100', 6);
@BravoNatalie this should be `ethers.utils.parseUnits('10', 6);` to get 10 million right?

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/4-purchase.ts
> +  const dropsPriceOracleAddress = '0xeA7f4C52cbD4CF1036CdCa8B16AcA11f5b09cF6E';
@BravoNatalie we should warn them not to change this value.

2024-05-01 23:06 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +- `2-purchase.ts`
@BravoNatalie this should be ascending.

2024-05-01 23:12 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +- `HOLOGRAPH_ENVIRONMENT`: Holograph environment (localhost, develop, testnet, mainnet)
@BravoNatalie Remove the reference to localhost here

2024-05-01 23:15 UTC, sogoiii commented on scripts/countdown_erc721/README.md
> +     - `countdownERC721Initializer`: Initializer object containing various parameters for the ERC721 contract
@BravoNatalie Specify the key names that they should modify.

2024-05-02 15:16 UTC, alexanderattar approved these changes

2024-05-02 15:16 UTC, merged