Migration/holograph factory test
holographxyz/v2 pull request #320
Opened 2024-05-29 13:31 UTC by fgregoribattista

## Describe Changes

- The tests are mostly solved. Remains to mitigate two test failures due to signature validation problems.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] All Foundry tests are passing

2024-05-29 23:26 UTC, djaciel approved these changes
LGTM

2024-05-30 16:59 UTC, sogoiii requested changes

2024-05-30 16:59 UTC, sogoiii commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    console.log(block.chainid);
This is duplicated.

2024-05-30 16:59 UTC, sogoiii commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
This test should be failing right? Since it has an invalid signature.

2024-05-30 16:59 UTC, sogoiii commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
the invalidSignature should be on the s variable not the v variable.

2024-05-30 16:59 UTC, sogoiii commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
Here the signature needs to be correct but the submitter is some OTHER address.

2024-05-30 20:50 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
Done!

2024-05-30 20:50 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
Done!

2024-05-30 20:51 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    console.log(block.chainid);
Yes, this is the test I am working on. Where we are having problems when the factory runs the holographer init at deployed.
take out the duplicate

2024-05-30 20:51 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
the signature was in error.  Done!

2024-05-30 20:52 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
rare that the test is passing with the wrong signature.
Once I finish the init, I'll see what this functionality does with the payload.

2024-05-31 17:30 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +    Verification memory signature = Verification({v: uint8(bytes1(invalidSignature)), r: r, s: s});
passed since the validation is given on the other two parts of the signature. 
The test is correct

2024-05-31 19:09 UTC, lucas-marc commented on test/foundry/deploy/11_HolographFactory.t.sol
> +  function getConfigHtokenETH() public view returns (DeploymentConfig memory, bytes32) {
nitpick: would be nice to have some description comments on this methods. Also, some spacing between functions!

2024-05-31 22:20 UTC, fgregoribattista commented on test/foundry/deploy/11_HolographFactory.t.sol
> +  function getConfigHtokenETH() public view returns (DeploymentConfig memory, bytes32) {
Done!

2024-06-03 07:05 UTC, sogoiii approved these changes

2024-06-03 21:50 UTC, alexanderattar approved these changes

2024-06-03 21:50 UTC, merged