Feature/holo 530 holograph genesis tests
holographxyz/v2 pull request #49
Opened 2022-10-11 05:59 UTC by alexanderattar

## Describe Changes

- Add tests for HolographGenesis

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] All Hardhat tests are passing

2022-10-11 15:56 UTC, ACC01ADE commented on deploy/02_sources.ts
> +            ['address', 'address', 'address', 'address'],
@alexanderattar I think there is older deploy scripts code in your commits. These changes would remove additional data for contracts in deployments and break everything. You might need to check the `experimental` branch and copy from it the contents of the `deploy/02_sources.ts` file.

2022-10-12 16:38 UTC, alexanderattar commented on src/mock/MockHolographGenesisChild.sol
> +  function IsApprovedDeployerMock(address deployer) external view returns (bool) {
lowercase the Is

2022-10-12 16:38 UTC, alexanderattar commented on src/mock/MockHolographGenesisChild.sol
> +  function IsApprovedDeployerMock(address deployer) external view returns (bool) {
this is done

2022-10-12 16:39 UTC, alexanderattar commented on deploy/02_sources.ts
>    const holographerBytecode: BytesLike = (await hre.ethers.getContractFactory('Holographer')).bytecode;
@ACC01ADE is this change intended?

2022-10-12 16:56 UTC, ackvf requested changes
Please remove stylistic (prettier) changes to unrelevant files you didn't directly touch. This is going to cause a lot of headaches to other pull requests.

2022-10-12 17:05 UTC, sogoiii approved these changes
👍

2022-10-12 17:43 UTC, merged